version: "3.8"

services:
  backend:
    build:
      context: ../HikeMeet-Backend
    ports:
      - "3000:3000"
    container_name: hike-backend

  frontend:
    build:
      context: .
    environment:
      - EXPO_LOCAL_SERVER=http://backend:3000
    depends_on:
      - backend
