version: "3.9"

services:
  backend:
    build:
      context: ./temp-backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    command: npm run dev

  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - "19000:19000"
      - "19006:19006"
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
    command: npm run start
    depends_on:
      - backend
