name: React Native Expo CI - Production

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Add more Node.js versions if needed

    steps:
      # Step 1: Checkout project repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run Linter Check (optional)
      #- name: Run Linter Check
      #  run: npm run lint

      # Step 5: Install Expo CLI
      - name: Install Expo CLI
        run: npm install -g expo eas-cli

      # Step 6: Build the Android app
      - name: Build Android App
        env:
          EXPO_TOKEN: ${{ secrets.CI_CD_TOKEN }}
        run: npx eas build --platform android --non-interactive

      # Step 7: Deploy the app (optional)
      #- name: Deploy App
      #  run: curl https://api.render.com/deploy/your-app-deploy-url
