name: Build and upload to production

on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install React Native dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Install Expo CLI
        run: npm install -g expo eas-cli

      - name: Build Android App
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas build --platform android --profile production --non-interactive
