name: Expo React Native CI with Node.js Backend

on:
  push:
    branches:
      - main
      - woozai-patch-1
      - feature/interactive-map-page2-include-test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # שלב 1: Checkout לפרונט
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      # שלב 2: Clone backend לריפו נפרד
      - name: Clone backend repo
        run: git clone https://github.com/HikeMeet/HikeMeet-Backend.git temp-backend

      # שלב 3: Build Docker image ל-backend (בלי compose!)
      - name: Build backend Docker image
        run: |
          docker build -t hike-backend ./temp-backend

      # שלב 4: הרצת השרת ברקע
      - name: Run backend server
        run: |
          docker run -d -p 3000:3000 --name backend-server hike-backend

      - name: Show backend container logs
        run: docker logs backend-server

      # שלב 5: וידוא שהשרת מוכן
      - name: Wait for backend to be ready
        run: |
          echo "Waiting for server..."
          until curl --silent http://localhost:3000/api; do
            sleep 2
            echo "Still waiting..."
          done
          echo "Server is up!"

      # שלב 6: Set up Node.js לפרונט
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"

      # שלב 7: התקנת תלויות
      - name: Install frontend dependencies
        run: npm install

      # שלב 8: הרצת בדיקות
      - name: Run frontend tests
        run: npm run test
