name: React Native Expo CI with Node.js Backend

on:
  push:
    branches:
      - cicd-roei-(test1)
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout React Native project repository
      - name: Checkout React Native Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js for React Native
      - name: Set up Node.js for React Native
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      # Step 3: Install React Native dependencies
      - name: Install React Native Dependencies
        run: npm ci

      # Step 4: Run Linter Check (optional)
      #- name: Run Linter
      #  run: npx eslint .

      # Step 5: Clone the backend repository
      - name: Clone Backend Repository
        run: git clone https://github.com/HikeMeet/HikeMeet-Backend.git backend

      # Step 6: Set up Node.js for the backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      # Step 7: Install backend dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      # Step 8: Start the backend server
      - name: Start Backend Server
        working-directory: ./backend
        run: |
          nohup npm start &
          sleep 10

      # Step 9: Run API Tests (optional)
      #- name: Run API Tests
      #  run: npm run test:api

      # Step 10: Install Expo CLI
      - name: Install Expo CLI
        run: npm install -g expo eas-cli

      # Step 11: Build the Android app
      - name: Build Android App
        env:
          EXPO_TOKEN: ${{ secrets.CI_CD_TOKEN }}
        run: npx eas build --platform android --non-interactive
