name: Expo React Native CI with Node.js Backend

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout frontend
      - name: Checkout frontend
        uses: actions/checkout@v4

      # 2. Clone backend
      - name: Clone backend
        run: git clone https://github.com/HikeMeet/HikeMeet-Backend.git temp-backend

      # 3. Docker Compose: build and start services
      - name: Start backend and frontend using Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      # 4. Debug logs: check backend container logs
      - name: Show backend logs
        run: docker logs hike-backend || echo "No logs available"

      # 5. Check backend health
      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend..."
          timeout 90 bash -c '
          until curl --silent http://localhost:3000/api; do
            sleep 2
            echo "Still waiting..."
          done
          echo "✅ Backend is UP!"

      # 6. Set up Node.js (locally for running tests)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      # 7. Install deps (outside container for running tests)
      - name: Install frontend dependencies
        run: npm install

      # 8. Run tests
      - name: Run frontend tests
        run: npm run test
