name: Expo React Native CI with Node.js Backend

on:
  push:
    branches:
      - main
      - woozai-patch-1
      - feature/interactive-map-page2-include-test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the React Native repository
      - uses: actions/checkout@v4

      # Set up Node.js for the React Native app
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"

          # Install dependencies for the React Native app
      - name: Install React Native dependencies
        run: npm install

      #- name: Run linter
      #  run: npm run lint

      # הרצת השרת בקונטיינר
      - name: Start backend server in Docker
        run: docker compose up -d

      # המתנה שהשרת יעלה (אפשר להחליף ב-healthcheck אם רוצים)
      - name: Wait for backend to be ready
        run: |
          echo "Waiting for server..."
          until curl --silent http://localhost:4000/health; do
            sleep 2
            echo "Still waiting for server..."
          done
          echo "Server is up!"

      # הרצת הבדיקות
      - name: Run tests
        run: npm run test
