name: Expo React Native CI with Node.js Backend

on:
  push:
    branches:
      - main
      - woozai-patch-1
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the React Native repository
      - uses: actions/checkout@v4

      # Set up Node.js for the React Native app
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      # Install dependencies for the React Native app
      - name: Install React Native dependencies
        run: npm install

      - name: Eslionter test
        run: npx eslint .

      # Clone the Node.js backend repository
      - name: Clone backend repository
        run: git clone https://github.com/HikeMeet/HikeMeet-Backend.git backend

      # # Set up Node.js for the backend
      # - name: Set up Node.js for backend
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18.x
      #     cache: "npm"

      # # Install backend dependencies
      # - name: Install backend dependencies
      #   working-directory: ./backend
      #   run: npm install

      # # Start the backend server
      # - name: Start backend server
      #   working-directory: ./backend
      #   run: |
      #     nohup npm start &
      #     sleep 10

      # Run tests for the React Native app
      #- name: Run tests
      #  run: npm test

      # Ensure the React Native app builds
      - name: Build React Native project
        run: expo build:android --non-interactive || expo prebuild --non-interactive
