#
name: Expo React Native CI with Node.js Backend

on:
  push:
    branches:
      - main
      - woozai-patch-1
      - feature/interactive-map-page2-include-test
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v4

      - name: Clone Backend Repo
        run: git clone https://github.com/HikeMeet/HikeMeet-Backend.git ../hikemeet-backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Containers
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend..."
          for i in {1..30}; do
            if curl -s http://localhost:5000/api | grep -q "Server is working"; then
              echo "✅ Backend is up!"
              exit 0
            fi
            echo "⏳ Waiting for backend... ($i)"
            sleep 2
          done
          echo "❌ Backend did not respond in time"
          docker logs hikemeet-backend || true
          exit 1

      - name: Run Frontend Tests
        run: docker exec hikemeet-frontend npm test
