name: Expo React Native CI with Node.js Backend

on:
  push:
    branches:
      - main
      - woozai-patch-1
      - feature/interactive-map-page2-include-test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout frontend repo
      - name: Checkout frontend
        uses: actions/checkout@v4

      # Step 2: Clone backend repo
      - name: Clone backend repo
        run: git clone https://github.com/HikeMeet/HikeMeet-Backend.git temp-backend

      # Step 3: Start backend and frontend using Docker Compose
      - name: Start backend and frontend using Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      # Step 4: Wait for backend to be ready
      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend..."
          until curl --silent http://localhost:3000/api; do
            sleep 2
            echo "Still waiting..."
          done
          echo "Backend is up!"

      # Step 5: Setup Node.js for tests
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      # Step 6: Install dependencies and run frontend tests
      - name: Install frontend dependencies
        run: npm install

      - name: Run frontend tests
        run: npm run test
