name: Expo React Native CI with Node.js Backend

on:
  push:
    branches:
      - main
      - woozai-patch-1
      - feature/interactive-map-page2-include-test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # שלב 1: Checkout לפרונט
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      # שלב 2: Clone ל-backend repo
      - name: Clone backend repo
        run: git clone https://github.com/HikeMeet/HikeMeet-Backend.git temp-backend

      # שלב 3: הרצת כל השירותים בבת אחת בעזרת Docker Compose
      - name: Start backend and frontend using Docker Compose
        run: docker compose up -d --build

      # שלב 4: הצגת לוגים של השרת (לצורכי דיבאג)
      - name: Show backend logs
        run: docker logs backend

      # שלב 5: המתנה לוודא שהשרת עלה (בדיקת API)
      - name: Wait for backend to be ready
        run: |
          echo "Waiting for server..."
          until curl --silent http://localhost:4000/api; do
            sleep 2
            echo "Still waiting..."
          done
          echo "Server is up!"

      # שלב 6: הגדרת Node.js לבדיקות של הפרונט
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"

      # שלב 7: התקנת תלויות לבדיקות מקומיות בפרונט (מחוץ ל-Docker)
      - name: Install frontend dependencies
        run: npm install

      # שלב 8: הרצת בדיקות של הפרונט
      - name: Run frontend tests
        run: npm run test
