name: Expo React Native CI with Node.js Backend

on:
  push:
    branches:
      - main
      - woozai-patch-1
      - feature/interactive-map-page2-include-test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout frontend (root repo)
      - name: Checkout code
        uses: actions/checkout@v4

      # Start backend and frontend using Docker Compose
      - name: Start backend and frontend using Docker Compose
        working-directory: ./HikeMeet-Fronted
        run: docker compose up -d --build

      # Wait until backend is ready (via API check)
      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend..."
          until curl --silent http://localhost:3000/api/health; do
            sleep 2
            echo "Still waiting..."
          done
          echo "Backend is up!"

      # Install Node.js for frontend tests (outside container)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: HikeMeet-Fronted/package-lock.json

      # Install dependencies & run tests locally (not in Docker)
      - name: Install frontend dependencies
        working-directory: HikeMeet-Fronted
        run: npm install

      - name: Run frontend tests
        working-directory: HikeMeet-Fronted
        run: npm run test
